<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBIJxqeE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBIJxqeE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBIJxqeE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBIJxqeE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBIJxqeE\App_KernelDevDebugContainer([
    'container.build_hash' => 'BIJxqeE',
    'container.build_id' => '9f4b1ceb',
    'container.build_time' => 1594224195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBIJxqeE');
