<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEIB2Pxv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEIB2Pxv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEIB2Pxv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEIB2Pxv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEIB2Pxv\App_KernelDevDebugContainer([
    'container.build_hash' => 'EIB2Pxv',
    'container.build_id' => '3bec02e1',
    'container.build_time' => 1594119696,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEIB2Pxv');
