<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEcJRQCt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEcJRQCt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEcJRQCt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEcJRQCt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEcJRQCt\App_KernelDevDebugContainer([
    'container.build_hash' => 'EcJRQCt',
    'container.build_id' => 'f7e21a82',
    'container.build_time' => 1593862784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEcJRQCt');
